# Generated by Django 2.2.7 on 2019-11-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Основные данные: тел, график и т.д', 'verbose_name_plural': 'Основные данные: тел, график и т.д'},
        ),
        migrations.AlterModelOptions(
            name='slideinhome',
            options={'verbose_name': 'Текст в слайд на главную', 'verbose_name_plural': 'Тексты в слайд на главную'},
        ),
        migrations.AddField(
            model_name='home',
            name='slider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='tv_backend.SlideInHome'),
            preserve_default=False,
        ),
    ]
