# Generated by Django 2.2.7 on 2019-11-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv_backend', '0003_auto_20191112_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideinhome',
            name='home_data',
        ),
        migrations.AddField(
            model_name='home',
            name='slider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='tv_backend.SlideInHome'),
            preserve_default=False,
        ),
    ]
