# Generated by Django 2.2.7 on 2019-11-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_backend', '0005_auto_20191112_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideinhome',
            name='image',
            field=models.ImageField(default=1, upload_to='./media/slider/'),
            preserve_default=False,
        ),
    ]
