# Generated by Django 2.2.7 on 2019-11-13 20:55

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_backend', '0006_slideinhome_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesAboutOfMalfunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Оглавление')),
                ('content', tinymce.models.HTMLField(blank=True, max_length=50000, verbose_name='Текст статьи')),
            ],
            options={
                'verbose_name': 'Статья о неисправности',
                'verbose_name_plural': 'Статьи о неисправностях',
            },
        ),
        migrations.AlterField(
            model_name='slideinhome',
            name='image',
            field=models.ImageField(upload_to='./slider/'),
        ),
        migrations.CreateModel(
            name='TypesOfMalfunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='./TypesOfMalfunctions_icon/', verbose_name='Иконка  в левом углу')),
                ('title', models.CharField(max_length=50, verbose_name='Оглавление')),
                ('content', tinymce.models.HTMLField(blank=True, max_length=500, verbose_name='Контент')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_backend.PagesAboutOfMalfunctions')),
            ],
            options={
                'verbose_name': 'Возможные неисправности > "после слайда"',
                'verbose_name_plural': 'Возможные неисправности > "после слайда"',
            },
        ),
    ]
