# Generated by Django 2.2.7 on 2019-11-17 16:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_backend', '0007_auto_20191113_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Оглавление')),
                ('content', tinymce.models.HTMLField(blank=True, max_length=5000, verbose_name='Контент')),
                ('image', models.ImageField(upload_to='./home/', verbose_name='Картинка с право')),
            ],
            options={
                'verbose_name': 'Блок о нас на главной',
                'verbose_name_plural': 'Блок о нас на главной',
            },
        ),
    ]
