# Generated by Django 2.2.7 on 2019-11-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_backend', '0008_aboutinhome'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAboutOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Оглавление')),
                ('sub_title', models.CharField(max_length=200, verbose_name='Оглавление')),
                ('video', models.FileField(upload_to='./home/', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Блок о заказе на главной',
                'verbose_name_plural': 'Блок о заказе на главной',
            },
        ),
    ]
