# Generated by Django 3.0 on 2019-12-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_backend', '0009_infoaboutorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoaboutorder',
            name='sub_title',
            field=models.CharField(max_length=200, verbose_name='Доп оглавление'),
        ),
        migrations.AlterField(
            model_name='infoaboutorder',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Оглавление'),
        ),
    ]
