# Generated by Django 3.0 on 2020-02-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_backend', '0010_auto_20191215_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_flag', models.BooleanField(default=True, verbose_name='Показывать отзыв на сайте?')),
                ('name_user', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('user_photo_link', models.URLField(verbose_name='Фото профиля')),
                ('review', models.TextField(max_length=1000, verbose_name='Отзыв клиента')),
                ('review_rate', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='кол-во звезд')),
            ],
            options={
                'verbose_name': 'Отзыв на Яндекс',
                'verbose_name_plural': 'Отзывы на Яндекс',
            },
        ),
    ]
