# Generated by Django 3.0 on 2020-04-28 00:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_backend', '0012_auto_20200428_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesaboutofmalfunctions',
            name='content',
            field=models.TextField(blank=True, max_length=50000, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='typesofmalfunctions',
            name='content',
            field=tinymce.models.HTMLField(blank=True, max_length=500, verbose_name='Контент'),
        ),
    ]
