# Generated by Django 3.0 on 2020-04-29 12:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_backend', '0013_auto_20200428_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesaboutofmalfunctions',
            name='content',
            field=tinymce.models.HTMLField(blank=True, max_length=50000, verbose_name='Текст статьи'),
        ),
    ]
