# Generated by Django 3.0 on 2020-04-18 18:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя сотрудника')),
                ('area', models.CharField(blank=True, max_length=50, verbose_name='Зона ответственности')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Зона ответственности')),
                ('avatar', models.ImageField(upload_to='./state_avatar', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Дополнительные сотрудник (футер)',
                'verbose_name_plural': 'Дополнительные сотрудники (футер)',
                'db_table': 'AdditionalStaff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CenterInFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(height_field=150, upload_to='./logo_footer', verbose_name='Логотип в футере', width_field=150)),
                ('content', tinymce.models.HTMLField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Лого и текст в центр футера',
                'verbose_name_plural': 'Лого и текст в центр футера',
                'db_table': 'CenterInFooter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SaleInFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sale', models.CharField(blank=True, max_length=50, verbose_name='Название акции')),
                ('description_sale', models.CharField(blank=True, max_length=150, verbose_name='Короткое описание акции')),
                ('size_sale', models.IntegerField(verbose_name='Размер скидки')),
            ],
            options={
                'verbose_name': 'Акция в подвале',
                'verbose_name_plural': 'Скидки и Акции в подвале',
                'db_table': 'SaleInFooter',
                'managed': True,
            },
        ),
    ]
