# Generated by Django 3.0 on 2020-04-28 00:08

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalstaff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Контактный номер'),
        ),
        migrations.AlterField(
            model_name='centerinfooter',
            name='content',
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='centerinfooter',
            name='logo',
            field=models.ImageField(upload_to='./logo_footer', verbose_name='Логотип в футере'),
        ),
    ]
