# Generated by Django 3.0 on 2020-04-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malfunks',
            name='malfunk',
            field=models.CharField(choices=[('1', 'статья 1'), ('2', 'статья 6'), ('3', 'статья 5'), ('4', 'статья внутри 4'), ('5', 'статья 2')], max_length=100, verbose_name='Тип неисправности'),
        ),
    ]
