# Generated by Django 3.0 on 2020-05-02 03:31

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('prew_img', models.ImageField(upload_to='./portfolio/', verbose_name='Основное фото')),
                ('content', tinymce.models.HTMLField(blank=True, max_length=1000, null=True, verbose_name='Текст-Статья')),
            ],
            options={
                'verbose_name': 'Фото и контент',
                'verbose_name_plural': 'Фото и контент',
                'db_table': 'Portfolio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PortfolioImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='./portfolio/', verbose_name='Дополнительное фото')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stor', to='portfolio.Portfolio')),
            ],
            options={
                'verbose_name': 'Дополнительные фото',
                'verbose_name_plural': 'Дополнительные фото',
                'db_table': 'portfolio_img',
                'managed': True,
            },
        ),
    ]
