# Generated by Django 3.0 on 2020-03-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_order', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип заказа')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя заказчика')),
                ('time_call', models.TimeField(verbose_name='Звонить в')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон')),
            ],
        ),
    ]
