# Generated by Django 3.0 on 2020-04-29 12:35

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя сотрудника')),
                ('avatar', models.ImageField(upload_to='./avatar_staff/', verbose_name='Фото сотрудника')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Должность')),
                ('text', tinymce.models.HTMLField(blank=True, max_length=200, verbose_name='Коротко о себе')),
            ],
            options={
                'verbose_name': 'Основной штат сотрудников',
                'verbose_name_plural': 'Основной штат сотрудников ',
                'db_table': 'Staff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AboutStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='./video_staff', verbose_name='видео на стр. о сотрудниках')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Штат', to='staff.Staff')),
            ],
            options={
                'verbose_name': 'Видео + Основной штат сотрудников',
                'verbose_name_plural': 'Видео + Основной штат сотрудников ',
                'db_table': 'Staff_Video',
                'managed': True,
            },
        ),
    ]
