# Generated by Django 3.0 on 2020-04-29 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutstaff',
            name='staff',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Видео', to='staff.AboutStaff'),
            preserve_default=False,
        ),
    ]
